# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/hdl/zedboard.xdc

# Block Designs: bd/staged_mac_bd/staged_mac_bd.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==staged_mac_bd || ORIG_REF_NAME==staged_mac_bd} -quiet] -quiet

# IP: bd/staged_mac_bd/ip/staged_mac_bd_axi_fifo_mm_s_0_0/staged_mac_bd_axi_fifo_mm_s_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==staged_mac_bd_axi_fifo_mm_s_0_0 || ORIG_REF_NAME==staged_mac_bd_axi_fifo_mm_s_0_0} -quiet] -quiet

# IP: bd/staged_mac_bd/ip/staged_mac_bd_processing_system7_0_0/staged_mac_bd_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==staged_mac_bd_processing_system7_0_0 || ORIG_REF_NAME==staged_mac_bd_processing_system7_0_0} -quiet] -quiet

# IP: bd/staged_mac_bd/ip/staged_mac_bd_ps7_0_axi_periph_0/staged_mac_bd_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==staged_mac_bd_ps7_0_axi_periph_0 || ORIG_REF_NAME==staged_mac_bd_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/staged_mac_bd/ip/staged_mac_bd_rst_ps7_0_100M_0/staged_mac_bd_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==staged_mac_bd_rst_ps7_0_100M_0 || ORIG_REF_NAME==staged_mac_bd_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/staged_mac_bd/ip/staged_mac_bd_staged_mac_0_0/staged_mac_bd_staged_mac_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==staged_mac_bd_staged_mac_0_0 || ORIG_REF_NAME==staged_mac_bd_staged_mac_0_0} -quiet] -quiet

# IP: bd/staged_mac_bd/ip/staged_mac_bd_axis_subset_converter_0_0/staged_mac_bd_axis_subset_converter_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==staged_mac_bd_axis_subset_converter_0_0 || ORIG_REF_NAME==staged_mac_bd_axis_subset_converter_0_0} -quiet] -quiet

# IP: bd/staged_mac_bd/ip/staged_mac_bd_auto_pc_0/staged_mac_bd_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==staged_mac_bd_auto_pc_0 || ORIG_REF_NAME==staged_mac_bd_auto_pc_0} -quiet] -quiet

# XDC: bd/staged_mac_bd/staged_mac_bd_ooc.xdc
