
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 
* DO NOT EDIT.
*
* Copyright (C) 2010-2026 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xaxicdma.h"

/*
* The configuration table for devices
*/

XAxiCdma_Config XAxiCdma_ConfigTable[XPAR_XAXICDMA_NUM_INSTANCES] =
{
	{
		XPAR_SYSTEM_DMA_DEVICE_ID,
		XPAR_SYSTEM_DMA_BASEADDR,
		XPAR_SYSTEM_DMA_INCLUDE_DRE,
		XPAR_SYSTEM_DMA_USE_DATAMOVER_LITE,
		XPAR_SYSTEM_DMA_M_AXI_DATA_WIDTH,
		XPAR_SYSTEM_DMA_M_AXI_MAX_BURST_LEN,
		XPAR_SYSTEM_DMA_ADDR_WIDTH
	}
};


