
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 
* DO NOT EDIT.
*
* Copyright (C) 2010-2026 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xintc.h"


extern void XNullHandler (void *);

/*
* The configuration table for devices
*/

XIntc_Config XIntc_ConfigTable[] =
{
	{
		XPAR_INTER_CONT_DEVICE_ID,
		XPAR_INTER_CONT_BASEADDR,
		XPAR_INTER_CONT_KIND_OF_INTR,
		XPAR_INTER_CONT_HAS_FAST,
		XPAR_INTER_CONT_IVAR_RESET_VALUE,
		XPAR_INTER_CONT_NUM_INTR_INPUTS,
		XPAR_INTER_CONT_ADDR_WIDTH,
		XIN_SVC_SGL_ISR_OPTION,
		XPAR_INTER_CONT_TYPE,
		{
			{
				XNullHandler,
				(void *) XNULL
			}
		}

	}
};

